"""Interactive processes — pexpect, for the class of commands bash cannot run.

The bash tool pipes stdin from nowhere, so anything that asks a question
mid-run (ssh host-key confirmation, a sudo password, fdisk, an installer, a
REPL) blocks until the timeout kills it. This tool spawns the program on a
pseudo-terminal and answers its prompts from a script the model supplies up
front, which keeps it one tool instead of a stateful spawn/send/expect trio.

A step's answer can come from two places: `send` (a literal string, the
model writes it directly) or `send_env` (the NAME of an environment
variable — `os.environ` is read for the actual value locally, in this
process, never by the model). `send_env` exists for exactly one reason: a
literal `send` means the actual secret has to be generated by the model to
appear in the tool call at all — round-tripping it through the model's own
context and Anthropic's API twice (once in, once out) even though
`secret: true` keeps it out of the RETURNED transcript afterward. Naming an
env var instead means the model only ever sees/writes a NAME, and the real
value is resolved by this module's own Python code, on this machine, never
touching a prompt or a completion. Same `token_env`/`api_key_env`-name-not-
value pattern this project's own `config.toml` already uses everywhere else
for secrets, applied here to interactive credential prompts specifically.
Always treated as secret for transcript purposes regardless of the `secret`
field — there is no scenario where naming an env var and then printing its
resolved value back into a transcript the model reads makes sense.

Deliberately no file-based equivalent (`send_file`, briefly added and then
removed the same session) — a literal env var, freshly `export`ed into an
interactive shell, requires no new persistent artifact at all; a file-based
version requires the secret to be written to disk in plain text as a matter
of normal use, which is a strictly worse default. An env var is not immune
to ending up on disk either (shell history if typed interactively and not
suppressed, or a startup file if `export`ed there for persistence) — this
tool cannot enforce how the caller manages the variable it names — but it
does not REQUIRE a new plaintext file to exist the way a file-based option
would.

A third source, `send_secret`, closes that remaining gap for real: the NAME
of a `pass` (the standard unix password manager, passwordstore.org) entry —
resolved locally via `pass show <name>`, whose real value is genuinely
encrypted at rest (GPG), not plaintext-if-you're-careful the way `send_env`
is. `pass`/`gnupg`/`pinentry-curses` need no GUI, no D-Bus session, no
desktop environment of any kind — confirmed to work identically on a
graphical desktop or a bare SSH-only server, and available (directly or via
EPEL) on Ubuntu/Debian/Fedora/Arch/RHEL/CentOS/Oracle Linux 8+ (RHEL-family
7 is the one real gap — `pass` was dropped from EPEL7 in 2019). Rejected
`secret-tool`/libsecret for this same purpose: it requires a D-Bus Secret
Service daemon tied to a logged-in graphical session (GNOME Keyring, KDE's
ksecretd — confirmed both can be running simultaneously on the SAME machine,
live, on this one), which simply doesn't exist on a headless server at all —
not a "which desktop environment" gap, a "no desktop environment" gap.
`pass` has no such requirement.

Requires:  pip install pexpect
"""

import asyncio
import json
import os
import subprocess
from pathlib import Path

from core.claude_learned_schemas import SHELL_EXECUTABLE, apply_shell_prelude
from core.output import clip

TOOLS = [
    {
        "name": "interactive_run",
        "description": (
            "Run a command that PROMPTS for input, answering its prompts from a "
            "script. Use this instead of bash whenever a program asks a question "
            "mid-run — password challenges, ssh host-key confirmation, "
            "'Are you sure? [y/N]', partitioning tools, installers, or a REPL — "
            "since the bash tool has no stdin and will simply hang. Each step "
            "waits for a regex to appear, then sends a line. For a password or "
            "token specifically, use a step's `send_env`/`send_secret` "
            "instead of `send` — the real value is read locally (from an "
            "environment variable, or from a `pass` password-store entry for "
            "genuine at-rest encryption) and never has to be written into "
            "this call at all, unlike a literal `send`, which the user has "
            "to tell you and you have to write down to use. Returns JSON "
            "with the terminal transcript and the exit status."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "string",
                    "description": (
                        "Shell command to spawn on a pty, e.g. "
                        "'ssh user@host uptime'."
                    ),
                },
                "steps": {
                    "type": "array",
                    "description": (
                        "Prompt/response pairs, applied in order. Omit for a "
                        "command that only needs a pty and no answers."
                    ),
                    "items": {
                        "type": "object",
                        "properties": {
                            "expect": {
                                "type": "string",
                                "description": (
                                    "Regex to wait for, e.g. 'password:' or "
                                    "'\\[y/N\\]'."
                                ),
                            },
                            "send": {
                                "type": "string",
                                "description": (
                                    "Literal line to send once it matches. "
                                    "Exactly one of `send`/`send_env`/"
                                    "`send_secret` is required per step. Use "
                                    "this for non-secret input (a username, "
                                    "'yes', a menu choice) — for a password "
                                    "or token, use `send_env`/`send_secret` "
                                    "instead so the real value never has to "
                                    "be written into this call at all."
                                ),
                            },
                            "send_env": {
                                "type": "string",
                                "description": (
                                    "Name of an environment variable — its "
                                    "value is read locally and sent, never "
                                    "written into this tool call. Use for a "
                                    "password/token/passphrase: the user "
                                    "sets the variable in their own shell "
                                    "ahead of time (out of band, never told "
                                    "to you), you only ever name it here. "
                                    "Always treated as secret in the "
                                    "returned transcript, regardless of the "
                                    "`secret` field. Errors clearly if the "
                                    "named variable isn't set, before "
                                    "spawning anything."
                                ),
                            },
                            "send_secret": {
                                "type": "string",
                                "description": (
                                    "Name of a `pass` (the standard unix "
                                    "password manager) entry — resolved "
                                    "locally via `pass show <name>` and "
                                    "sent, never written into this tool "
                                    "call. Prefer this over `send_env` when "
                                    "genuine at-rest encryption matters: a "
                                    "`pass` entry is GPG-encrypted on disk, "
                                    "unlike an env var, which is only "
                                    "plaintext-free if the user is careful "
                                    "about how they set it. Needs no "
                                    "desktop environment or GUI — works "
                                    "identically on a headless server. "
                                    "Always treated as secret in the "
                                    "returned transcript, regardless of the "
                                    "`secret` field. Errors clearly if "
                                    "`pass`/the named entry isn't available, "
                                    "before spawning anything. Don't know "
                                    "which entry to use? Pass the literal "
                                    "string \"?\" instead of a real name — "
                                    "this returns a fixed, ready-to-relay "
                                    "prompt built from the real vault "
                                    "contents (\"please select the cred "
                                    "name I need to use:\" plus every real "
                                    "entry), not something to guess at or "
                                    "compose yourself."
                                ),
                            },
                            "secret": {
                                "type": "boolean",
                                "description": (
                                    "Redact this step's `send` response from "
                                    "the returned transcript. Only meaningful "
                                    "for a literal `send` — `send_env`/"
                                    "`send_secret` are always redacted "
                                    "unconditionally, since their entire "
                                    "point is keeping the real value out of "
                                    "anything you see."
                                ),
                            },
                        },
                        "required": ["expect"],
                    },
                },
                "timeout": {
                    "type": "integer",
                    "description": (
                        "Seconds to wait for each prompt and for the program to "
                        "finish (default 30)."
                    ),
                },
            },
            "required": ["command"],
        },
    }
]

_TOOL_NAMES = {t["name"] for t in TOOLS}
_MAX_TRANSCRIPT = 12000
_DEFAULT_TIMEOUT = 30
# How long `send_secret`'s `pass show` subprocess gets before giving up —
# see `_resolve_reply`'s own docstring for why this exists at all (an
# unanswerable pinentry prompt with no terminal here would otherwise hang
# for the full interactive_run timeout). A plain module attribute, not a
# function default, specifically so test_processes.py can shrink it instead
# of a real test run actually waiting out the production value.
_SEND_SECRET_TIMEOUT = 10

# Entry names that have already been explicitly presented AND re-referenced
# once, for the life of this process — see `_resolve_reply`'s own docstring
# for the incident this closes: a real live session skipped straight to
# `"send_secret": "sudo_admin"` on the FIRST attempt, without ever showing
# the "please select the cred name I need to use:" prompt first, because
# nothing forced it to — the "?" sentinel only helps if the caller chooses
# to use it, and this one didn't, even though "sudo_admin" was the only
# entry that existed. A module-level set, not a function default, because
# it has to persist across separate `_run()` calls within the same running
# process to mean anything.
_confirmed_secret_entries: set[str] = set()


def handles(name: str) -> bool:
    return name in _TOOL_NAMES


async def execute(name: str, tool_input: dict) -> str:
    if name != "interactive_run":
        return json.dumps({"error": f"unknown process tool {name!r}"})
    return await asyncio.to_thread(_run, tool_input)


def _resolve_reply(step: dict) -> tuple[str, bool, str | None]:
    """Return (reply_text, is_secret, error) for one step.

    Exactly one of `send`/`send_env`/`send_secret` must be present —
    anything else (zero, or more than one) is a caller error, returned as
    `error` rather than silently guessing which one was meant. `send_env`/
    `send_secret` always come back with `is_secret=True`; a literal `send`
    respects the step's own `secret` field (default `False`), matching this
    tool's existing behavior for that case unchanged.

    `send_secret` shells out to `pass show <name>` with a 10-second timeout,
    not an unbounded wait — if `pass`/`gpg` end up needing a passphrase
    prompt (the GPG key isn't already unlocked in `gpg-agent`'s cache) there
    is no terminal here for `pinentry` to use, so this would otherwise hang
    for the full `interactive_run` timeout on top of whatever the REAL
    command's own steps needed, indistinguishable from a genuine hang. The
    error message says so explicitly rather than just "timed out" — unlock
    the key once, manually, in a real terminal first, which caches it in
    `gpg-agent` for a while and lets subsequent calls succeed silently.
    """
    sources = [k for k in ("send", "send_env", "send_secret") if k in step]
    if len(sources) == 0:
        return "", False, "must include one of `send`, `send_env`, `send_secret`"
    if len(sources) > 1:
        return "", False, f"only one of `send`/`send_env`/`send_secret` allowed, got {sources}"

    if "send" in step:
        return str(step["send"]), bool(step.get("secret")), None

    if "send_env" in step:
        var_name = str(step["send_env"])
        value = os.environ.get(var_name)
        if value is None:
            return "", False, f"environment variable {var_name!r} is not set"
        return value, True, None

    entry_name = str(step["send_secret"])
    if entry_name == "?" or entry_name not in _confirmed_secret_entries:
        # First reference to this exact name (or an explicit "?") — refuse
        # to use it yet, REGARDLESS of whether it's real, correct, or the
        # only entry that exists. Recording it here means the NEXT call
        # that names this same entry is treated as the confirmed one — so
        # a real task still only takes two calls total (present, then use),
        # not a repeated prompt every single time the same entry comes up
        # later in the same session.
        _confirmed_secret_entries.add(entry_name)
        return "", False, _select_entry_prompt()

    try:
        result = subprocess.run(
            ["pass", "show", entry_name],
            capture_output=True,
            text=True,
            timeout=_SEND_SECRET_TIMEOUT,
            check=False,
        )
    except FileNotFoundError:
        return "", False, "`pass` is not installed (see the module docstring for setup)"
    except subprocess.TimeoutExpired:
        return "", False, (
            f"`pass show {entry_name!r}` did not return within "
            f"{_SEND_SECRET_TIMEOUT}s — likely waiting on a GPG passphrase "
            "prompt with no terminal here to answer it. Unlock the key "
            "once, manually, in your own terminal (`pass show ...` there) "
            "first — gpg-agent caches it for a while afterward, and this "
            "call will then succeed silently."
        )
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip() or "unknown error"
        return "", False, f"`pass show {entry_name!r}` failed: {detail}{_available_entries_hint()}"
    first_line = result.stdout.splitlines()[0] if result.stdout else ""
    return first_line, True, None


def _select_entry_prompt() -> str:
    """The exact, hardcoded text returned when a step uses `"send_secret": "?"`
    — the caller's explicit way of saying "I need a credential here but don't
    know which vault entry to use." Builds a fixed-format message from the
    REAL entries in the vault; nothing about the wording is left to whatever
    composes the final reply to the user. That's the whole point: which
    entries actually exist, and how the request for one is phrased, are both
    decided here, in code, not by a model that might wrap it in an
    explanation, phrase it as a vague hypothetical, or ask as an open-ended
    question — no version of that was reliable in practice, confirmed live,
    more than once, on real interactive_run credential prompts.

    Reads `$PASSWORD_STORE_DIR` (falling back to `~/.password-store`, `pass`'s
    own documented default) and walks it directly for `*.gpg` files, rather
    than parsing `pass ls`'s own tree-drawing output — found live, while
    building this, that naively stripping `pass ls`'s box-drawing characters
    loses FOLDER STRUCTURE for a nested entry (`aws/prod` rendered under an
    `aws` branch came out as bare `prod`, which is not a valid `pass show`
    argument on its own). Walking the real files gives the exact, full
    relative path for every entry, unambiguously, matching what `pass show`
    actually needs. No decryption happens here — `.gpg` filenames are read
    directly off the filesystem, never opened.
    """
    store_dir = Path(os.environ.get("PASSWORD_STORE_DIR", "~/.password-store")).expanduser()
    if not store_dir.is_dir():
        return f"no password store found at {store_dir} — nothing to select"
    entries = sorted(
        str(p.relative_to(store_dir))[: -len(".gpg")]
        for p in store_dir.rglob("*.gpg")
    )
    if not entries:
        return "the password store is empty — nothing to select"
    return "please select the cred name I need to use:\n" + "\n".join(entries)


def _available_entries_hint() -> str:
    """Appended to a `send_secret` failure message: the real list of entry
    NAMES currently in the vault (never their values — `pass ls` is a pure
    directory listing, confirmed live it needs no passphrase and touches no
    encrypted content at all). Exists specifically so a wrong or made-up
    entry name doesn't just fail blind — the caller sees what's actually
    there immediately, in the same error, rather than needing a separate
    round trip to ask "what do you even have?" This is a safety net, not a
    substitute for the actual rule: never pick which entry to use by
    guessing among what's listed here — a human names the exact entry for
    every real task, every time. Best-effort — if `pass ls` itself fails for
    any reason, the base error above is still returned on its own.
    """
    try:
        result = subprocess.run(
            ["pass", "ls"],
            capture_output=True,
            text=True,
            timeout=5,
            check=False,
        )
    except Exception:
        return ""
    if result.returncode != 0 or not result.stdout.strip():
        return ""
    return f"\n\nEntries actually in the vault:\n{result.stdout.strip()}"


def _redact(transcript: str, secret_values: list[str]) -> str:
    """Replace every occurrence of every value in `secret_values` anywhere
    in `transcript` with `***` — not just the one line where a step
    actually sent it.

    This is the fix for a real, live-caught bug, not a defensive-only
    measure: the previous design only ever substituted "***" at the exact
    call site that SENT a secret reply, which correctly hid it from that one
    line but did nothing about the child process printing the same value
    back out on its OWN, later, as unrelated output (confirmed live: a
    prompt/echo test script — `read -s -p ...; echo "GOT:[$val]"` — put a
    real `pass`-sourced secret in plain text into the returned transcript,
    on the `echo` line, which this function's call site never touched
    before). Scrubbing the complete, final transcript for every known
    secret value, wherever it appears, closes that gap regardless of why or
    how the value ended up repeated. Empty values are skipped — replacing
    "" would insert `***` between every character.
    """
    for value in set(secret_values):
        if value:
            transcript = transcript.replace(value, "***")
    return transcript


def _run(tool_input: dict) -> str:
    try:
        import pexpect
    except ImportError:
        return json.dumps(
            {
                "error": "pexpect is not installed — `pip install pexpect` to "
                "enable the interactive_run tool"
            }
        )

    command = tool_input.get("command", "")
    if not command.strip():
        return json.dumps({"error": "no command provided"})

    steps = tool_input.get("steps") or []
    timeout = int(tool_input.get("timeout") or _DEFAULT_TIMEOUT)

    # Resolve every step's actual reply text AND whether it counts as secret
    # up front, before spawning anything — a missing env var or unreadable
    # file is a configuration error the caller should see immediately, not
    # something that surfaces only after a real program has already been
    # left mid-prompt (ssh half-connected, an installer half-run) by a step
    # further down the list.
    resolved_replies: list[tuple[str, bool]] = []
    for i, step in enumerate(steps):
        reply, is_secret, error = _resolve_reply(step)
        if error:
            return json.dumps({"error": f"step {i}: {error}"})
        resolved_replies.append((reply, is_secret))

    transcript: list[str] = []
    matched = 0
    timed_out_at = None

    try:
        child = pexpect.spawn(
            SHELL_EXECUTABLE,
            ["-c", apply_shell_prelude(command)],
            encoding="utf-8",
            codec_errors="replace",
            timeout=timeout,
            echo=False,
        )
    except Exception as e:
        return json.dumps({"error": f"could not spawn command: {e}"})

    try:
        for step, (reply, is_secret) in zip(steps, resolved_replies, strict=True):
            pattern = str(step.get("expect", ""))
            try:
                child.expect(pattern)
            except pexpect.TIMEOUT:
                timed_out_at = pattern
                break
            except pexpect.EOF:
                timed_out_at = None
                transcript.append(child.before or "")
                break

            transcript.append((child.before or "") + (child.after or ""))
            child.sendline(reply)
            # Appended here as the real value, unconditionally -- NOT "***"
            # even when `is_secret` is true. Redaction happens exactly once,
            # at the very end, via `_redact()` over the COMPLETE transcript
            # (see that function's own docstring for why appending "***"
            # only at this one call site was the actual bug: it missed the
            # secret entirely if the child process later echoed it back on
            # its own, in unrelated output this code never touches here).
            transcript.append(reply + "\n")
            matched += 1

        # Drain whatever the program prints after the last answer.
        try:
            child.expect(pexpect.EOF)
            transcript.append(child.before or "")
        except pexpect.TIMEOUT:
            transcript.append(child.before or "")
            if timed_out_at is None:
                timed_out_at = "(waiting for the program to exit)"
    finally:
        try:
            child.close(force=True)
        except (OSError, pexpect.ExceptionPexpect) as e:
            print(f"[processes] child.close failed (ignored): {e}")

    full_transcript = _redact(
        "".join(transcript),
        secret_values=[reply for reply, is_secret in resolved_replies if is_secret],
    )

    return json.dumps(
        {
            "transcript": clip(full_transcript, _MAX_TRANSCRIPT),
            "steps_matched": matched,
            "steps_total": len(steps),
            "exit_status": child.exitstatus,
            "signal_status": child.signalstatus,
            "timed_out_waiting_for": timed_out_at,
        }
    )
