"""Interactive processes — pexpect, for the class of commands bash cannot run.

The bash tool pipes stdin from nowhere, so anything that asks a question
mid-run (ssh host-key confirmation, a sudo password, fdisk, an installer, a
REPL) blocks until the timeout kills it. This tool spawns the program on a
pseudo-terminal and answers its prompts from a script the model supplies up
front, which keeps it one tool instead of a stateful spawn/send/expect trio.

A step's answer can come from two places: `send` (a literal string, the
model writes it directly) or `send_env` (the NAME of an environment
variable — `os.environ` is read for the actual value locally, in this
process, never by the model). `send_env` exists for exactly one reason: a
literal `send` means the actual secret has to be generated by the model to
appear in the tool call at all — round-tripping it through the model's own
context and Anthropic's API twice (once in, once out) even though
`secret: true` keeps it out of the RETURNED transcript afterward. Naming an
env var instead means the model only ever sees/writes a NAME, and the real
value is resolved by this module's own Python code, on this machine, never
touching a prompt or a completion. Same `token_env`/`api_key_env`-name-not-
value pattern this project's own `config.toml` already uses everywhere else
for secrets, applied here to interactive credential prompts specifically.
Always treated as secret for transcript purposes regardless of the `secret`
field — there is no scenario where naming an env var and then printing its
resolved value back into a transcript the model reads makes sense.

Deliberately no file-based equivalent (`send_file`, briefly added and then
removed the same session) — a literal env var, freshly `export`ed into an
interactive shell, requires no new persistent artifact at all; a file-based
version requires the secret to be written to disk in plain text as a matter
of normal use, which is a strictly worse default. An env var is not immune
to ending up on disk either (shell history if typed interactively and not
suppressed, or a startup file if `export`ed there for persistence) — this
tool cannot enforce how the caller manages the variable it names — but it
does not REQUIRE a new plaintext file to exist the way a file-based option
would. Real at-rest protection (encrypted, unlocked via the desktop session
rather than sitting in plain text either way) would mean a proper OS-keyring
integration (`secret-tool`/libsecret is already installed on this machine)
instead — a genuinely different, stronger mechanism, not implemented here.

Requires:  pip install pexpect
"""

import asyncio
import json
import os

from core.claude_learned_schemas import SHELL_EXECUTABLE, apply_shell_prelude
from core.output import clip

TOOLS = [
    {
        "name": "interactive_run",
        "description": (
            "Run a command that PROMPTS for input, answering its prompts from a "
            "script. Use this instead of bash whenever a program asks a question "
            "mid-run — password challenges, ssh host-key confirmation, "
            "'Are you sure? [y/N]', partitioning tools, installers, or a REPL — "
            "since the bash tool has no stdin and will simply hang. Each step "
            "waits for a regex to appear, then sends a line. For a password or "
            "token specifically, use a step's `send_env` instead of `send` — "
            "the real value is read locally from an environment variable and "
            "never has to be written into this call at all, unlike a literal "
            "`send`, which the user has to tell you and you have to write "
            "down to use. Returns JSON with the terminal transcript and the "
            "exit status."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "string",
                    "description": (
                        "Shell command to spawn on a pty, e.g. "
                        "'ssh user@host uptime'."
                    ),
                },
                "steps": {
                    "type": "array",
                    "description": (
                        "Prompt/response pairs, applied in order. Omit for a "
                        "command that only needs a pty and no answers."
                    ),
                    "items": {
                        "type": "object",
                        "properties": {
                            "expect": {
                                "type": "string",
                                "description": (
                                    "Regex to wait for, e.g. 'password:' or "
                                    "'\\[y/N\\]'."
                                ),
                            },
                            "send": {
                                "type": "string",
                                "description": (
                                    "Literal line to send once it matches. "
                                    "Exactly one of `send`/`send_env` is "
                                    "required per step. Use this for "
                                    "non-secret input (a username, 'yes', a "
                                    "menu choice) — for a password or "
                                    "token, use `send_env` instead so the "
                                    "real value never has to be written "
                                    "into this call at all."
                                ),
                            },
                            "send_env": {
                                "type": "string",
                                "description": (
                                    "Name of an environment variable — its "
                                    "value is read locally and sent, never "
                                    "written into this tool call. Use for a "
                                    "password/token/passphrase: the user "
                                    "sets the variable in their own shell "
                                    "ahead of time (out of band, never told "
                                    "to you), you only ever name it here. "
                                    "Always treated as secret in the "
                                    "returned transcript, regardless of the "
                                    "`secret` field. Errors clearly if the "
                                    "named variable isn't set, before "
                                    "spawning anything."
                                ),
                            },
                            "secret": {
                                "type": "boolean",
                                "description": (
                                    "Redact this step's `send` response from "
                                    "the returned transcript. Only meaningful "
                                    "for a literal `send` — `send_env` is "
                                    "always redacted unconditionally, since "
                                    "its entire point is keeping the real "
                                    "value out of anything you see."
                                ),
                            },
                        },
                        "required": ["expect"],
                    },
                },
                "timeout": {
                    "type": "integer",
                    "description": (
                        "Seconds to wait for each prompt and for the program to "
                        "finish (default 30)."
                    ),
                },
            },
            "required": ["command"],
        },
    }
]

_TOOL_NAMES = {t["name"] for t in TOOLS}
_MAX_TRANSCRIPT = 12000
_DEFAULT_TIMEOUT = 30


def handles(name: str) -> bool:
    return name in _TOOL_NAMES


async def execute(name: str, tool_input: dict) -> str:
    if name != "interactive_run":
        return json.dumps({"error": f"unknown process tool {name!r}"})
    return await asyncio.to_thread(_run, tool_input)


def _resolve_reply(step: dict) -> tuple[str, bool, str | None]:
    """Return (reply_text, is_secret, error) for one step.

    Exactly one of `send`/`send_env` must be present — anything else (zero,
    or both) is a caller error, returned as `error` rather than silently
    guessing which one was meant. `send_env` always comes back with
    `is_secret=True`; a literal `send` respects the step's own `secret`
    field (default `False`), matching this tool's existing behavior for
    that case unchanged.
    """
    sources = [k for k in ("send", "send_env") if k in step]
    if len(sources) == 0:
        return "", False, "must include one of `send`, `send_env`"
    if len(sources) > 1:
        return "", False, f"only one of `send`/`send_env` allowed, got {sources}"

    if "send" in step:
        return str(step["send"]), bool(step.get("secret")), None

    var_name = str(step["send_env"])
    value = os.environ.get(var_name)
    if value is None:
        return "", False, f"environment variable {var_name!r} is not set"
    return value, True, None


def _run(tool_input: dict) -> str:
    try:
        import pexpect
    except ImportError:
        return json.dumps(
            {
                "error": "pexpect is not installed — `pip install pexpect` to "
                "enable the interactive_run tool"
            }
        )

    command = tool_input.get("command", "")
    if not command.strip():
        return json.dumps({"error": "no command provided"})

    steps = tool_input.get("steps") or []
    timeout = int(tool_input.get("timeout") or _DEFAULT_TIMEOUT)

    # Resolve every step's actual reply text AND whether it counts as secret
    # up front, before spawning anything — a missing env var or unreadable
    # file is a configuration error the caller should see immediately, not
    # something that surfaces only after a real program has already been
    # left mid-prompt (ssh half-connected, an installer half-run) by a step
    # further down the list.
    resolved_replies: list[tuple[str, bool]] = []
    for i, step in enumerate(steps):
        reply, is_secret, error = _resolve_reply(step)
        if error:
            return json.dumps({"error": f"step {i}: {error}"})
        resolved_replies.append((reply, is_secret))

    transcript: list[str] = []
    matched = 0
    timed_out_at = None

    try:
        child = pexpect.spawn(
            SHELL_EXECUTABLE,
            ["-c", apply_shell_prelude(command)],
            encoding="utf-8",
            codec_errors="replace",
            timeout=timeout,
            echo=False,
        )
    except Exception as e:
        return json.dumps({"error": f"could not spawn command: {e}"})

    try:
        for step, (reply, is_secret) in zip(steps, resolved_replies, strict=True):
            pattern = str(step.get("expect", ""))
            try:
                child.expect(pattern)
            except pexpect.TIMEOUT:
                timed_out_at = pattern
                break
            except pexpect.EOF:
                timed_out_at = None
                transcript.append(child.before or "")
                break

            transcript.append((child.before or "") + (child.after or ""))
            child.sendline(reply)
            transcript.append("***\n" if is_secret else reply + "\n")
            matched += 1

        # Drain whatever the program prints after the last answer.
        try:
            child.expect(pexpect.EOF)
            transcript.append(child.before or "")
        except pexpect.TIMEOUT:
            transcript.append(child.before or "")
            if timed_out_at is None:
                timed_out_at = "(waiting for the program to exit)"
    finally:
        try:
            child.close(force=True)
        except (OSError, pexpect.ExceptionPexpect) as e:
            print(f"[processes] child.close failed (ignored): {e}")

    return json.dumps(
        {
            "transcript": clip("".join(transcript), _MAX_TRANSCRIPT),
            "steps_matched": matched,
            "steps_total": len(steps),
            "exit_status": child.exitstatus,
            "signal_status": child.signalstatus,
            "timed_out_waiting_for": timed_out_at,
        }
    )
